description "Compass extension based on the HTML5 Boilerplate styles generated for Scorpion project"

stylesheet 'application.scss', :media => 'all'
stylesheet 'style.scss', :media => 'all', :to => "scorpion/style.scss"
stylesheet 'partials/_base.scss', :to => "scorpion/partials/_base.scss"
stylesheet 'partials/_overrides.scss', :to => "scorpion/partials/_overrides.scss"
stylesheet 'partials/_fonts.scss', :to => "scorpion/partials/_fonts.scss"
stylesheet 'partials/_media.scss', :to => "scorpion/partials/_media.scss"
stylesheet 'partials/_page.scss', :to => "scorpion/partials/_page.scss"

help %Q{
This is a Compass extension based on the styles created for the Scorpion project.
The original project was based on the compass-html5-boilerplate gem and the structure matches
the files generated by that gem (See full docs at: http://github.com/sporkd/compass-html5-boilerplate)

Rails Installation
========================
$ gem install compass-head_start
$ cd my_rails_project
$ compass init rails -r compass-head_start -u compass-head_start/scorpion --force

Stand Alone Installation not supported

}

welcome_message %Q{
You've installed Scorpion styles. Good for you!

}
